### PR TITLE
Add notebooks to the publishing cycle

### PR DESCRIPTION
**Pull request by tonyfast**
This pull request adds a github pages deployment to the blog.  The pages deployment will convert notebooks in the `_notebooks` to markdown `_posts`.   The post front matter is constructed from the notebook metadata and git revision histories.

This approach allows notebooks to be reused on binder for demonstration and read as blog documents.

[Binder](https://mybinder.org/v2/gh/Quansight/Quansight.github.io/notebooks)

Currently, the builds are passing on demo branches.  

This is a decent start.  I welcome any comments or ideas.

### CODE REVIEW

**Comment by scopatz** [comment]
This looks good to me! Any reason not to merge it?

**Comment by scopatz** [comment]
Maybe add some text to the readme about writing notebook entries?

**Comment by tonyfast** [comment]
I'll have to change the branches that the travis build is pointing to.  

There is a little bit of a procedural question.  Github pages deploys on specific branches, we don't want to publish preemptively otherwise an incomplete may be published.  

We could either use a specific build branch like `publish`, add a `_wip` folder, or we could use the jekyll [`published` flags](http://www.fizerkhan.com/blog/posts/Working-with-upcoming-posts-in-Jekyll.html). 

I should probably turn the notebook I used to get this running into an actual document.

- [ ] Decide on a preferred way to submit new posts and drafts.
- [ ] Create a pull_request_template with instructions for submitting a new post.
- [ ] Turn the notebook used to make this into a post.

**Comment by tonyfast** [comment]
I still have to work on the pull request template with some instructions for making a post.  

The build is now pointing at master and updating the blog. 

Here is an [example blog post](https://quansight.github.io/Computable-posts-from-quansight/).  Is there anyway you could take a look at it and see if we want to keep it?

**Comment by scopatz** [comment]
That post looks great! It would be great to be have this. I'll review the PR again

**Comment by saulshanabrook** [comment]
This looks fun!



I would like to put an `environment.yml` or something per post so that Binder would pick this up. However Binder only seems to work as an environment per repository, see https://mybinder.readthedocs.io/en/latest/using.html


So I think what we could do is have one folder per notebook blog post. When it is published, we create a commit on a branch that is the name of the blog post. The contents of the repo in that branch are the contents of the folder. Then the binder link for each post points to that branch, so that it picks up any build files in that folder.

**Comment by saulshanabrook** [comment]
If this is merged, I can create a PR to try that out.

**Comment by tonyfast** [comment]
We should use `environment.yml` instead of `requirements.txt`.  There could be a `postBuild` file that registers environments for each of the specific posts.  The environments info could be stored in the notebook metadata.

**Comment by saulshanabrook** [comment]
> We should use environment.yml instead of requirements.txt. There could be a postBuild file that registers environments for each of the specific posts. The environments info could be stored in the notebook metadata.


Sorry I don't think I was very explicit above, I meant just specifying build files for Binder to use not for us to use on Travis. For binder to use them, they could be any of their supported files but they have to be in a specific location in the repository (in the root or in the `binder` folder). So my suggestion was to make a commit for each post that has only the notebook and the binder config files in it, so that when you launch binder with that commit it picks up the right build information.

**Comment by tonyfast** [comment]
That is a cool idea.  So each branch has an `environment.yml` that can be used explicitly.  Maybe master only uses `requirements.txt` so it builds faster.

**Comment by saulshanabrook** [comment]
New branches for every notebook, that are created automatically, and have at the root whatever files you put in the folder for that notebook. i.e. in master you have structure: `_notebooks/<notebook-name>/notebook.ipynb` and `_notebooks/<notebook-name>/<whatever-other-file>`. Where `<whatever-other-file>` could be `environment.yml` or `postBuild` or `requirements.txt`, any file that binder recognizes (or just any file in general). Then we do some magic in Travis CI to make a new branch called `<notebook-name>` that has the contents of the `_notebooks/<notebook-name>` in the root of the repo. So when we tell binder to build that branch it picks up the right files.

So on every travis CI build it makes new commits to all notebook branches with the right files and pushes those.

**Comment by saulshanabrook** [comment]
Note: existing nbconvert in travis would behave the same with what I proposed, this would only be to change launch in binder behavior.

**Comment by tonyfast** [comment]
I dig that.  Can you have a go at post and we'll use that to give this a go the first time?

**Comment by scopatz** [comment]
Is there anything else that we need to do here?

**Comment by tonyfast** [comment]
lgtm.  hopefully someone could try writing another post.

**Pull request merged**
