### PR TITLE
Create 2018-12-19-Episode-10-Sparse.md

### PR DESCRIPTION
**Pull request by bsodenkamp**

### CODE REVIEW

**Comment by scopatz** [comment]
LGTM @hameerabbasi - can you please review this too?

**Comment by hameerabbasi** [comment]
I’ll get to this tomorrow morning, hopefully.

**Comment by scopatz** [comment]
@bsodenkamp - would you mind applying these typo fixes, please? Thanks!

**Comment by scopatz** [comment]
LGTM Thanks @bsodenkamp!

**Pull request merged**
